#!/bin/bash
set -euo pipefail

mk_tty_keymap() {
    local keymap_dir=/usr/share/kbd/keymaps/i386/qwerty/
    gunzip --stdout "$keymap_dir"/us.map.gz |
        sed -E '/^keycode +58/c keycode  58 = Control' |
        gzip - |
        sudo tee "$keymap_dir"/jat.map.gz >/dev/null
}

set_custom() {
    local repo_dir
    repo_dir=$(cd "${BASH_SOURCE%/*}/.." && pwd || return 1)

    # Since we're just setting the X11 keymap temporarily with xkbcomp, also set the
    # X11 keymap to us+ctrl:nocaps to get most of what we want if the layout
    # gets reset for some reason.
    #
    # Expect a bunch of warnings from xkbcomp about unresolvable keysyms and
    # unassigned keycodes.
    mk_tty_keymap &&
    sudo localectl set-keymap --no-convert jat &&
    sudo localectl set-x11-keymap --no-convert us '' '' ctrl:nocaps &&
    xkbcomp "$repo_dir"/dotfiles/keymap.xkb "$DISPLAY" 2>/dev/null
}

set_builtin() {
    sudo localectl set-keymap --no-convert us &&
    sudo localectl set-x11-keymap --no-convert us '' '' ctrl:nocaps
}

if [[ $# -eq 0 ]]; then
    set_custom
else
    "$@"
fi
