#!/bin/bash
set -euo pipefail

[[ $EUID -eq 0 ]] || {
    echo "must be run as root" >&2
    exit 1
}

keymap_dir=/usr/share/kbd/keymaps/i386/qwerty/
gunzip --stdout "$keymap_dir"/us.map.gz |
    sed -E '/^keycode +58/c keycode  58 = Control' |
    gzip - >"$keymap_dir"/jat.map.gz
mkinitcpio -p linux
